<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn New Java Features' Course: New Features in Java 12-17</description>
    <name>new-features-in-java-12-17</name>

    <groupId>com.baeldung</groupId>
    <artifactId>lnj-new-features-in-java-12-17</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>pattern-matching-instanceof-start</module>
        <module>pattern-matching-instanceof-end</module>
        <module>multi-line-strings-with-text-blocks-start</module>
        <module>multi-line-strings-with-text-blocks-end</module>
        <module>records-start</module>
        <module>records-end</module>
        <module>switch-expressions-start</module>
        <module>switch-expressions-end</module>
        <module>stream-api-additions-java-12-17-start</module>
        <module>stream-api-additions-java-12-17-end</module>
        <module>sealed-classes-start</module>
        <module>sealed-classes-end</module>
    </modules>
</project>
